### ISSUE TITLE
Is the project waiting for development?

### ISSUE THREAD

**Issue by C1oky** [NovaPlayPE/JBServer#6]
I noticed that there are no commits lately. And there are no answers to pull requests. What is the reason for this? And is it worth the wait for an improvement in the situation?

**Comment by Ragnok123** [comment]
Project is developing. However, I'm working on NBT unique retranslators (because on JE and BE they're a bit different) to make changes in level structure.

**Comment by C1oky** [comment]
Good. But it seems to me, it was necessary to separate this task into a separate branch and allow other developers to trace the history. At the end of the work, make merge branches and there would be no problems

**Comment by Ragnok123** [comment]
I made different branch for a world, so now it's possible to do pull requests.
